// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin/challenges" | "/admin/dashboard" | "/admin/feature-toggles" | "/admin/register" | "/admin/reports" | "/admin/transactions" | "/android" | "/login" | "/user/challenges" | "/user/challenges/[id]" | "/user/dashboard" | "/user/online-transfer" | "/user/passbook" | "/user/personal-finance" | "/user/qr-transfer" | "/user/quiz" | "/user/reports"
type AppRouteHandlerRoutes = "/api/admin/calc-interest" | "/api/admin/challenges" | "/api/admin/challenges/[id]/finish" | "/api/admin/challenges/[id]/start" | "/api/admin/recalculate-accrued-interest" | "/api/admin/reports" | "/api/auth/[...nextauth]" | "/api/challenges" | "/api/challenges/[id]" | "/api/challenges/complete" | "/api/challenges/join" | "/api/challenges/submit" | "/api/challenges/user/[userId]" | "/api/quiz" | "/api/quiz/leaderboard" | "/api/quiz/stats/[userId]" | "/api/quiz/subCategory" | "/api/quiz/wiki" | "/api/quotes/commodities" | "/api/quotes/mutual-fund" | "/api/quotes/stock" | "/api/run-interest" | "/api/run-manual-interest" | "/api/schemes" | "/api/schemes/[id]" | "/api/settings" | "/api/transactions" | "/api/transactions/pay-loan" | "/api/transactions/transfer" | "/api/transactions/transfer-fd" | "/api/transactions/withdraw-fd" | "/api/user/finance/add-asset" | "/api/user/finance/add-cashflow" | "/api/user/finance/add-liability" | "/api/user/finance/delete-asset" | "/api/user/finance/delete-cashflow" | "/api/user/finance/delete-liability" | "/api/user/finance/list-assets" | "/api/user/finance/list-cashflows" | "/api/user/finance/list-liabilities" | "/api/user/finance/networth" | "/api/user/finance/update-asset" | "/api/user/finance/update-cashflow" | "/api/user/finance/update-liability" | "/api/user/reports" | "/api/users" | "/api/users/[id]" | "/api/users/[id]/interest-rates" | "/api/users/[id]/mpin" | "/api/users/[id]/password" | "/api/users/[id]/qr-code" | "/api/users/[id]/reset-mpin" | "/api/users/[id]/reset-password" | "/api/users/[id]/transactions" | "/api/users/[id]/verify-mpin"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin/challenges": {}
  "/admin/dashboard": {}
  "/admin/feature-toggles": {}
  "/admin/register": {}
  "/admin/reports": {}
  "/admin/transactions": {}
  "/android": {}
  "/api/admin/calc-interest": {}
  "/api/admin/challenges": {}
  "/api/admin/challenges/[id]/finish": { "id": string; }
  "/api/admin/challenges/[id]/start": { "id": string; }
  "/api/admin/recalculate-accrued-interest": {}
  "/api/admin/reports": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/challenges": {}
  "/api/challenges/[id]": { "id": string; }
  "/api/challenges/complete": {}
  "/api/challenges/join": {}
  "/api/challenges/submit": {}
  "/api/challenges/user/[userId]": { "userId": string; }
  "/api/quiz": {}
  "/api/quiz/leaderboard": {}
  "/api/quiz/stats/[userId]": { "userId": string; }
  "/api/quiz/subCategory": {}
  "/api/quiz/wiki": {}
  "/api/quotes/commodities": {}
  "/api/quotes/mutual-fund": {}
  "/api/quotes/stock": {}
  "/api/run-interest": {}
  "/api/run-manual-interest": {}
  "/api/schemes": {}
  "/api/schemes/[id]": { "id": string; }
  "/api/settings": {}
  "/api/transactions": {}
  "/api/transactions/pay-loan": {}
  "/api/transactions/transfer": {}
  "/api/transactions/transfer-fd": {}
  "/api/transactions/withdraw-fd": {}
  "/api/user/finance/add-asset": {}
  "/api/user/finance/add-cashflow": {}
  "/api/user/finance/add-liability": {}
  "/api/user/finance/delete-asset": {}
  "/api/user/finance/delete-cashflow": {}
  "/api/user/finance/delete-liability": {}
  "/api/user/finance/list-assets": {}
  "/api/user/finance/list-cashflows": {}
  "/api/user/finance/list-liabilities": {}
  "/api/user/finance/networth": {}
  "/api/user/finance/update-asset": {}
  "/api/user/finance/update-cashflow": {}
  "/api/user/finance/update-liability": {}
  "/api/user/reports": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/api/users/[id]/interest-rates": { "id": string; }
  "/api/users/[id]/mpin": { "id": string; }
  "/api/users/[id]/password": { "id": string; }
  "/api/users/[id]/qr-code": { "id": string; }
  "/api/users/[id]/reset-mpin": { "id": string; }
  "/api/users/[id]/reset-password": { "id": string; }
  "/api/users/[id]/transactions": { "id": string; }
  "/api/users/[id]/verify-mpin": { "id": string; }
  "/login": {}
  "/user/challenges": {}
  "/user/challenges/[id]": { "id": string; }
  "/user/dashboard": {}
  "/user/online-transfer": {}
  "/user/passbook": {}
  "/user/personal-finance": {}
  "/user/qr-transfer": {}
  "/user/quiz": {}
  "/user/reports": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
