// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/challenges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/challenges">> = Specific
  const handler = {} as typeof import("../../src/app/admin/challenges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/feature-toggles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/feature-toggles">> = Specific
  const handler = {} as typeof import("../../src/app/admin/feature-toggles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/register">> = Specific
  const handler = {} as typeof import("../../src/app/admin/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/android/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/android">> = Specific
  const handler = {} as typeof import("../../src/app/android/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/challenges/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/challenges/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/user/challenges/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/challenges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/challenges">> = Specific
  const handler = {} as typeof import("../../src/app/user/challenges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/user/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/online-transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/online-transfer">> = Specific
  const handler = {} as typeof import("../../src/app/user/online-transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/passbook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/passbook">> = Specific
  const handler = {} as typeof import("../../src/app/user/passbook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/personal-finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/personal-finance">> = Specific
  const handler = {} as typeof import("../../src/app/user/personal-finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/qr-transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/qr-transfer">> = Specific
  const handler = {} as typeof import("../../src/app/user/qr-transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/quiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/quiz">> = Specific
  const handler = {} as typeof import("../../src/app/user/quiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/reports">> = Specific
  const handler = {} as typeof import("../../src/app/user/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/calc-interest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calc-interest">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/calc-interest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/challenges/[id]/finish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/challenges/[id]/finish">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/challenges/[id]/finish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/challenges/[id]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/challenges/[id]/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/challenges/[id]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/challenges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/challenges">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/challenges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/recalculate-accrued-interest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/recalculate-accrued-interest">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/recalculate-accrued-interest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/challenges/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/challenges/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/challenges/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/challenges/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/challenges/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/challenges/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/challenges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges">> = Specific
  const handler = {} as typeof import("../../src/app/api/challenges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/challenges/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/challenges/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/challenges/user/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/user/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/challenges/user/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quiz/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quiz/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/quiz/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quiz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quiz">> = Specific
  const handler = {} as typeof import("../../src/app/api/quiz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quiz/stats/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quiz/stats/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/quiz/stats/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quiz/subCategory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quiz/subCategory">> = Specific
  const handler = {} as typeof import("../../src/app/api/quiz/subCategory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quiz/wiki/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quiz/wiki">> = Specific
  const handler = {} as typeof import("../../src/app/api/quiz/wiki/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/commodities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/commodities">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/commodities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/mutual-fund/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/mutual-fund">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/mutual-fund/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/stock">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/run-interest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run-interest">> = Specific
  const handler = {} as typeof import("../../src/app/api/run-interest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/run-manual-interest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run-manual-interest">> = Specific
  const handler = {} as typeof import("../../src/app/api/run-manual-interest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/schemes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schemes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/schemes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/schemes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schemes">> = Specific
  const handler = {} as typeof import("../../src/app/api/schemes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transactions/pay-loan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transactions/pay-loan">> = Specific
  const handler = {} as typeof import("../../src/app/api/transactions/pay-loan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transactions/transfer-fd/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transactions/transfer-fd">> = Specific
  const handler = {} as typeof import("../../src/app/api/transactions/transfer-fd/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transactions/transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transactions/transfer">> = Specific
  const handler = {} as typeof import("../../src/app/api/transactions/transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transactions/withdraw-fd/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transactions/withdraw-fd">> = Specific
  const handler = {} as typeof import("../../src/app/api/transactions/withdraw-fd/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/add-asset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/add-asset">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/add-asset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/add-cashflow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/add-cashflow">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/add-cashflow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/add-liability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/add-liability">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/add-liability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/delete-asset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/delete-asset">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/delete-asset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/delete-cashflow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/delete-cashflow">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/delete-cashflow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/delete-liability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/delete-liability">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/delete-liability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/list-assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/list-assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/list-assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/list-cashflows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/list-cashflows">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/list-cashflows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/list-liabilities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/list-liabilities">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/list-liabilities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/networth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/networth">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/networth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/update-asset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/update-asset">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/update-asset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/update-cashflow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/update-cashflow">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/update-cashflow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/finance/update-liability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/finance/update-liability">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/finance/update-liability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/interest-rates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/interest-rates">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/interest-rates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/mpin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/mpin">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/mpin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/qr-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/qr-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/qr-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/reset-mpin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/reset-mpin">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/reset-mpin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/verify-mpin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/verify-mpin">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/verify-mpin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
